### ISSUE TITLE
Suggestion: smooth scrolling 😎 

### ISSUE THREAD

**Issue by sbinlondon** [fac-15/CCSM#8]
The website looks great. One suggestion for making it even more of a good UX is to add a smooth scroll behaviour. Currently when you click things on the hamburger menu, it jumps between sections.

Read up below to see how you can implement this:
https://www.w3schools.com/howto/howto_css_smooth_scroll.asp

**Comment by boi87** [comment]
Thank you for the suggestion! We'll look at that asap.

-CCSM Team

**Comment by charlielafosse** [comment]
smooth scroll feature added!

commit no. 810afa1 on STAGING branch
